
"use strict";

//library
var Fluxis = require('../src/index.js');


// test framework
var chai = require("chai");
var sinon = require("sinon");
var sinonChai = require("sinon-chai");
chai.should();
chai.use(sinonChai);


var action = require('./action/fake');
var store = require('./store/fake');




describe('Verify objects generated by fluxis.', function(){
  describe('Verify action object generated by fluxis.', function(){
    it('action shoul be a Object', function(){
      action.should.be.a('object');
    });
    it('action should be have doSomething function', function(){
      action['doSomething'].should.be.a('function');
    });
    it('action should be have doWithArgs function', function(){
      action['doWithArgs'].should.be.a('function');
    });
    it('action should be have doWithSelector function', function(){
      action['doWithSelector'].should.be.a('function');
    });
  });

  describe('Verify Store object generated by fluxis.', function(){
    it('Store should be a objecto', function(){
      store.should.be.a('object');
    });
    it('Store should be have doSomething function', function(){
      store['doSomething'].should.be.a('function');
    });
    it('Store should be have doWithArgs function', function(){
      store['doWithArgs'].should.be.a('function');
    });
    it('Store should be have doWithSelector function', function(){
      store['doWithSelector'].should.be.a('function');
    })    
  });
})
